export default
{
    "total_results":15,
    "total_pages":1,
    "per_page":20,
    "page":1,
    "association":[
      {
        "id":65499831,
        "is_waldec":"true",
        "id_association":"W9G1010991",
        "id_ex_association":null,
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"9G1P",
        "date_creation":"2021-05-31",
        "date_derniere_declaration":"2021-05-31",
        "date_publication_creation":"2021-06-08",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"CLTOUCH",
        "titre_court":"CLTOUCH",
        "objet":"développement, la promotion de l'art designer par la culture carnavalesque dans sa globalité ; Un domaine d'insertion, de formation des populations en marges de la société ; L'organisation d'actions et d'évènements de type carnaval, ou tous autres activités liées avec la culture, au spectacle et à la mode ; \nEn lien avec les activités et projets de l'association, elle fera partie intégrante des dispositifs lies à l'économie sociale et solidaire ;",
        "objet_social1":"006000",
        "objet_social2":"000000",
        "l1_adresse_import":null,
        "l2_adresse_import":null,
        "l3_adresse_import":null,
        "adresse_siege":"12 Residence le Concerto",
        "adresse_numero_voie":null,
        "adresse_repetition":null,
        "adresse_type_voie":"LD",
        "adresse_libelle_voie":"la Jaille",
        "adresse_distribution":"_",
        "adresse_code_insee":"97103",
        "adresse_code_postal":"97122",
        "adresse_libelle_commune":"Baie-Mahault",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":"12",
        "adresse_gestion_geo":"RESIDENCE LE CONCERTO",
        "adresse_gestion_libelle_voie":"LIEU DIT LA JAILLE",
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":"97122",
        "adresse_gestion_acheminement":"BAIE MAHAULT",
        "adresse_gestion_pays":"FRANCE",
        "dirigeant_civilite":"PM",
        "telephone":"0102030405",
        "site_web":"http://www.larueketanou.com",
        "email":"Jacques.Gtoland@gmal.com",
        "autorisation_publication_web":"0",
        "observation":null,
        "position_activite":"A",
        "derniere_maj":"2021-06-08 12:45:23",
        "created_at":"2022-05-03T02:04:15.000Z",
        "updated_at":"2022-05-03T02:04:15.000Z"
      },
      {
        "id":65788600,
        "is_waldec":"true",
        "id_association":"W751226327",
        "id_ex_association":null,
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"751P",
        "date_creation":"2014-10-02",
        "date_derniere_declaration":"2018-09-14",
        "date_publication_creation":"2014-10-18",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"CLT FRANCE",
        "titre_court":"CLT FRANCE",
        "objet":"développement des panneaux et des systèmes constructifs à base de lamellé croisé en bois, CLT, par la mise en place de toute action visant à accroître les débouchés par la technique, la normalisation, la qualité et la promotion ; représentation des membres auprès des pouvoirs publics et suivi des évolutions réglementaires ; assurer la représentativité des membres dans le cadre des travaux de normalisation européens et français ; élaboration de règles professionnelles, guides de mise en oeuvre et autres documents techniques ; mise en place d'actions techniques, technico économiques et de recherche et leur pilotage ; organisation de groupe de travail, constitué si besoin d'experts externes, pour traiter de sujets techniques particuliers liés aux aspects normatifs, environnementaux et réglementaires ; ester en justice à la demande d'un ou plusieurs de ses membres dans les conditions fixées par l'article 26",
        "objet_social1":"023040",
        "objet_social2":"002015",
        "l1_adresse_import":null,
        "l2_adresse_import":null,
        "l3_adresse_import":null,
        "adresse_siege":null,
        "adresse_numero_voie":"120",
        "adresse_repetition":null,
        "adresse_type_voie":"AV",
        "adresse_libelle_voie":"Ledru Rollin",
        "adresse_distribution":"_",
        "adresse_code_insee":"75111",
        "adresse_code_postal":"75011",
        "adresse_libelle_commune":"Paris",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":null,
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":"120  AVENUE LEDRU ROLLIN",
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":"75011",
        "adresse_gestion_acheminement":"PARIS 11E",
        "adresse_gestion_pays":"FRANCE",
        "dirigeant_civilite":"PM",
        "telephone":null,
        "site_web":null,
        "email":null,
        "autorisation_publication_web":"0",
        "observation":null,
        "position_activite":"A",
        "derniere_maj":"2018-12-06 10:21:53",
        "created_at":"2022-05-03T02:05:09.000Z",
        "updated_at":"2022-05-03T02:05:09.000Z"
      },
      {
        "id":65810093,
        "is_waldec":"true",
        "id_association":"W751250959",
        "id_ex_association":null,
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"931P",
        "date_creation":"2019-02-06",
        "date_derniere_declaration":"2019-11-02",
        "date_publication_creation":"2019-02-09",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"CULTURÉ (CLTR.)",
        "titre_court":"CLTR.",
        "objet":"promotion et accompagnement d'artistes français ou étrangers dans leur développement artistique en France et à l'étranger (communication, production, image et conseil) ; Création d'événements culturels en France et à l'étranger ; Développement grâce aux aides financières internes et externes pouvant émaner d'organismes privés ou publics ; Chaque membre pourra proposera ses projets à la direction lors des assemblées ; Les projets des membres seront étudiés et un budget prévisionnel sera établi afin de financer le projet après validation du conseil d'administration ; Le conseil d'administration se donne le droit de refuser un projet n'ayant aucun aspect artistique ; Les projets validés seront financés par l'association et les aides externes.",
        "objet_social1":"006100",
        "objet_social2":"022542",
        "l1_adresse_import":null,
        "l2_adresse_import":null,
        "l3_adresse_import":null,
        "adresse_siege":null,
        "adresse_numero_voie":"24",
        "adresse_repetition":null,
        "adresse_type_voie":"RUE",
        "adresse_libelle_voie":"Benjamin Delessert",
        "adresse_distribution":null,
        "adresse_code_insee":"93055",
        "adresse_code_postal":"93500",
        "adresse_libelle_commune":"Pantin",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":null,
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":"24 RUE BENJAMIN DELESSERT",
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":"93500",
        "adresse_gestion_acheminement":"PANTIN",
        "adresse_gestion_pays":"FRANCE",
        "dirigeant_civilite":"PM",
        "telephone":null,
        "site_web":null,
        "email":null,
        "autorisation_publication_web":"0",
        "observation":null,
        "position_activite":"A",
        "derniere_maj":"2020-05-03 20:00:03",
        "created_at":"2022-05-03T02:05:13.000Z",
        "updated_at":"2022-05-03T02:05:13.000Z"
      },
      {
        "id":64526309,
        "is_waldec":"true",
        "id_association":"W493001974",
        "id_ex_association":"0493002140",
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"493S",
        "date_creation":"1971-08-05",
        "date_derniere_declaration":"2014-11-05",
        "date_publication_creation":"1971-09-17",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"TERRES D'ECHANGES - CLTM",
        "titre_court":"CLTM",
        "objet":"grouper les personnes désireuses de s'intéresser activement aux questions économiques, humaines et culturelles des peuples du monde et d'établir des partenariats dans les pays concernés pour mener des projets de santé, d'éducation et de développement",
        "objet_social1":"020000",
        "objet_social2":"000000",
        "l1_adresse_import":null,
        "l2_adresse_import":null,
        "l3_adresse_import":null,
        "adresse_siege":"Centre social Jean Dima",
        "adresse_numero_voie":"5",
        "adresse_repetition":null,
        "adresse_type_voie":"PL",
        "adresse_libelle_voie":"de la Justice de Paix",
        "adresse_distribution":"_",
        "adresse_code_insee":"49125",
        "adresse_code_postal":"49700",
        "adresse_libelle_commune":"Doué-la-Fontaine",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":"1 place de la Mairie",
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":null,
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":"49540",
        "adresse_gestion_acheminement":"Tigné",
        "adresse_gestion_pays":"FRANCE",
        "dirigeant_civilite":"PF",
        "telephone":null,
        "site_web":null,
        "email":null,
        "autorisation_publication_web":"1",
        "observation":"Date de déclaration notée sur le JO : 2 septembre 1971",
        "position_activite":"A",
        "derniere_maj":"2014-11-20 15:55:12",
        "created_at":"2022-05-03T02:01:11.000Z",
        "updated_at":"2022-05-03T02:01:11.000Z"
      },
      {
        "id":66566455,
        "is_waldec":"false",
        "id_association":"691P0691025724",
        "id_ex_association":"0691025724",
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"691P",
        "date_creation":"0001-01-01",
        "date_derniere_declaration":null,
        "date_publication_creation":"1989-01-11",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"CLUB LOISIRS TRAVAIL (CLT)",
        "titre_court":null,
        "objet":"Amelioration du bien etre du quartier",
        "objet_social1":"022000",
        "objet_social2":"000000",
        "l1_adresse_import":"172 avenue saint exupery",
        "l2_adresse_import":null,
        "l3_adresse_import":null,
        "adresse_siege":null,
        "adresse_numero_voie":null,
        "adresse_repetition":null,
        "adresse_type_voie":null,
        "adresse_libelle_voie":null,
        "adresse_distribution":null,
        "adresse_code_insee":"69029",
        "adresse_code_postal":"69500",
        "adresse_libelle_commune":"BRON",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":null,
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":null,
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":null,
        "adresse_gestion_acheminement":null,
        "adresse_gestion_pays":null,
        "dirigeant_civilite":"PM",
        "telephone":null,
        "site_web":null,
        "email":null,
        "autorisation_publication_web":null,
        "observation":"Reprise auto =\u003e  date publication création au JO à vérifier",
        "position_activite":"A",
        "derniere_maj":"2004-06-21  06:56:17",
        "created_at":"2022-05-03T02:07:55.000Z",
        "updated_at":"2022-05-03T02:07:55.000Z"
      },
      {
        "id":64648594,
        "is_waldec":"true",
        "id_association":"W661001602",
        "id_ex_association":null,
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"661S",
        "date_creation":"2011-07-18",
        "date_derniere_declaration":"2022-01-17",
        "date_publication_creation":"2011-08-13",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"CLT DES ALBERES (CULTURE LOISIRS TRADITIIONS)",
        "titre_court":"CLT DES ALBERES",
        "objet":"perpétuer les traditions catalanes et découvrir le patrimoine catalan",
        "objet_social1":"010022",
        "objet_social2":"000000",
        "l1_adresse_import":null,
        "l2_adresse_import":null,
        "l3_adresse_import":null,
        "adresse_siege":"MAIRIE",
        "adresse_numero_voie":null,
        "adresse_repetition":null,
        "adresse_type_voie":null,
        "adresse_libelle_voie":"carrer  des Ecoles",
        "adresse_distribution":"_",
        "adresse_code_insee":"66225",
        "adresse_code_postal":"66740",
        "adresse_libelle_commune":"Villelongue-dels-Monts",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":"15 CHEMIN DU MOULIN",
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":null,
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":"66740",
        "adresse_gestion_acheminement":"MONTESQUIEU DES ALBERES",
        "adresse_gestion_pays":"FRANCE",
        "dirigeant_civilite":"PM",
        "telephone":null,
        "site_web":null,
        "email":null,
        "autorisation_publication_web":"0",
        "observation":null,
        "position_activite":"D",
        "derniere_maj":"2022-01-17 14:50:48",
        "created_at":"2022-05-03T02:01:35.000Z",
        "updated_at":"2022-05-03T02:01:35.000Z"
      },
      {
        "id":66838634,
        "is_waldec":"false",
        "id_association":"862S0862003464",
        "id_ex_association":"0862003464",
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"862S",
        "date_creation":"2001-06-20",
        "date_derniere_declaration":null,
        "date_publication_creation":"2001-07-14",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"CLUB LIZANTAIS DU TENNIS DE TABLE - CLTT",
        "titre_court":null,
        "objet":"FAIRE PRATIQUER LE TENNIS DE TABLE SOUS FORME SPORTIVE OU DE LOISIR ET D'ASSURER DES LIENS AMICAUX ENTRE LES ADHERENTS, PARTICIPER ACTIVEMENT Â L'OBTENTION DES OBJECTIFS QUE S'EST FIXE LA FEDERATION FRANCAISE DE TENNIS DE TABLE",
        "objet_social1":"000000",
        "objet_social2":"000000",
        "l1_adresse_import":"MAIRIE DE LIZANT",
        "l2_adresse_import":"LE BOURG",
        "l3_adresse_import":null,
        "adresse_siege":null,
        "adresse_numero_voie":null,
        "adresse_repetition":null,
        "adresse_type_voie":null,
        "adresse_libelle_voie":null,
        "adresse_distribution":null,
        "adresse_code_insee":"86136",
        "adresse_code_postal":"86400",
        "adresse_libelle_commune":"LIZANT",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":null,
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":null,
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":null,
        "adresse_gestion_acheminement":null,
        "adresse_gestion_pays":null,
        "dirigeant_civilite":"PM",
        "telephone":null,
        "site_web":null,
        "email":null,
        "autorisation_publication_web":null,
        "observation":null,
        "position_activite":"A",
        "derniere_maj":"2006-03-23  03:50:36",
        "created_at":"2022-05-03T02:08:37.000Z",
        "updated_at":"2022-05-03T02:08:37.000Z"
      },
      {
        "id":66901387,
        "is_waldec":"false",
        "id_association":"921S3139",
        "id_ex_association":"3139",
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"921S",
        "date_creation":"1985-06-17",
        "date_derniere_declaration":null,
        "date_publication_creation":"1990-06-20",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"CONSEIL DES LOCATAIRES DE LA TANNERIE  CLT",
        "titre_court":null,
        "objet":"VOIR STATUTS",
        "objet_social1":"000000",
        "objet_social2":"000000",
        "l1_adresse_import":"8 RUE DE LA BIEVRE",
        "l2_adresse_import":null,
        "l3_adresse_import":null,
        "adresse_siege":null,
        "adresse_numero_voie":null,
        "adresse_repetition":null,
        "adresse_type_voie":null,
        "adresse_libelle_voie":null,
        "adresse_distribution":null,
        "adresse_code_insee":"00000",
        "adresse_code_postal":"92220",
        "adresse_libelle_commune":null,
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":null,
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":null,
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":null,
        "adresse_gestion_acheminement":null,
        "adresse_gestion_pays":null,
        "dirigeant_civilite":"PM",
        "telephone":null,
        "site_web":null,
        "email":null,
        "autorisation_publication_web":null,
        "observation":null,
        "position_activite":"A",
        "derniere_maj":"2009-03-23  03:00:00",
        "created_at":"2022-05-03T02:08:46.000Z",
        "updated_at":"2022-05-03T02:08:46.000Z"
      },
      {
        "id":64620842,
        "is_waldec":"true",
        "id_association":"W452000403",
        "id_ex_association":"0454015852",
        "siret":"48273703800034",
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"452P",
        "date_creation":"2006-07-11",
        "date_derniere_declaration":"2021-12-13",
        "date_publication_creation":"2006-08-05",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"CERCLE LAIQUE DES TOURELLES ORLEANS BADMINTON (CLTO BADMINTON)",
        "titre_court":"CLTO BADMINTON",
        "objet":"PRATIQUE SPORTIVE DU BADMINTON AINSI QUE TOUTES LES ACTIONS PROPRES A PROMOUVOIR ET A VALORISER CE SPORT",
        "objet_social1":"011030",
        "objet_social2":"000000",
        "l1_adresse_import":null,
        "l2_adresse_import":null,
        "l3_adresse_import":null,
        "adresse_siege":null,
        "adresse_numero_voie":"1",
        "adresse_repetition":null,
        "adresse_type_voie":"BD",
        "adresse_libelle_voie":"de Québec",
        "adresse_distribution":"_",
        "adresse_code_insee":"45234",
        "adresse_code_postal":"45000",
        "adresse_libelle_commune":"Orléans",
        "adresse_gestion_nom":"Monsieur BANDOU-NAITOLL Steve",
        "adresse_gestion_format_postal":null,
        "adresse_gestion_geo":"PORTE 10",
        "adresse_gestion_libelle_voie":"20 RUE DES GRISETS",
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":"45650",
        "adresse_gestion_acheminement":"ST JEAN LE BLANC",
        "adresse_gestion_pays":"FRANCE",
        "dirigeant_civilite":"PM",
        "telephone":null,
        "site_web":"http://www.cltobadminton.fr",
        "email":null,
        "autorisation_publication_web":"0",
        "observation":"dernière date publication enregistrée :2007-09-15",
        "position_activite":"A",
        "derniere_maj":"2021-12-13 09:14:49",
        "created_at":"2022-05-03T02:01:30.000Z",
        "updated_at":"2022-05-03T02:01:30.000Z"
      },
      {
        "id":66579836,
        "is_waldec":"false",
        "id_association":"691P0691044230",
        "id_ex_association":"0691044230",
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"691P",
        "date_creation":"1999-07-27",
        "date_derniere_declaration":null,
        "date_publication_creation":"1999-08-21",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"COMITE DES LOCATAIRES DES TAMARIS ET DES BOULEAUX (CLTB)",
        "titre_court":null,
        "objet":"Comite d'informations et de defense des locataires des residences des tamaris et des bouleaux sur la commune de lissieu",
        "objet_social1":"022000",
        "objet_social2":"000000",
        "l1_adresse_import":"3 rue des tours",
        "l2_adresse_import":"Chez mme houdayer",
        "l3_adresse_import":null,
        "adresse_siege":null,
        "adresse_numero_voie":null,
        "adresse_repetition":null,
        "adresse_type_voie":null,
        "adresse_libelle_voie":null,
        "adresse_distribution":null,
        "adresse_code_insee":"69117",
        "adresse_code_postal":"69380",
        "adresse_libelle_commune":"LISSIEU",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":null,
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":null,
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":null,
        "adresse_gestion_acheminement":null,
        "adresse_gestion_pays":null,
        "dirigeant_civilite":"PM",
        "telephone":null,
        "site_web":null,
        "email":null,
        "autorisation_publication_web":null,
        "observation":null,
        "position_activite":"A",
        "derniere_maj":"2004-06-21  06:56:56",
        "created_at":"2022-05-03T02:07:57.000Z",
        "updated_at":"2022-05-03T02:07:57.000Z"
      },
      {
        "id":65104055,
        "is_waldec":"true",
        "id_association":"W133020924",
        "id_ex_association":null,
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"922P",
        "date_creation":"2014-01-07",
        "date_derniere_declaration":"2015-03-20",
        "date_publication_creation":"2014-02-01",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"COMMUNITY LAND TRUST FRANCE (CLT FRANCE, POUR UN FONCIER SOLIDAIRE)",
        "titre_court":"CLT FRANCE, POUR UN FONCIER SOLIDAIRE",
        "objet":"promouvoir en France, les principes, valeurs et modèle des Community Land Trust et en diffuser une compréhension commune",
        "objet_social1":"002000",
        "objet_social2":"000000",
        "l1_adresse_import":null,
        "l2_adresse_import":null,
        "l3_adresse_import":null,
        "adresse_siege":null,
        "adresse_numero_voie":"32",
        "adresse_repetition":null,
        "adresse_type_voie":"AV",
        "adresse_libelle_voie":"des Chartreux",
        "adresse_distribution":"_",
        "adresse_code_insee":"13204",
        "adresse_code_postal":"13004",
        "adresse_libelle_commune":"Marseille",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":null,
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":"32  avenue des Chartreux",
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":"13004",
        "adresse_gestion_acheminement":"Marseille",
        "adresse_gestion_pays":"FRANCE",
        "dirigeant_civilite":"PM",
        "telephone":null,
        "site_web":null,
        "email":null,
        "autorisation_publication_web":"0",
        "observation":null,
        "position_activite":"A",
        "derniere_maj":"2016-10-10 10:57:11",
        "created_at":"2022-05-03T02:03:00.000Z",
        "updated_at":"2022-05-03T02:03:00.000Z"
      },
      {
        "id":66896283,
        "is_waldec":"false",
        "id_association":"812S203250",
        "id_ex_association":"203250",
        "siret":"0",
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"812S",
        "date_creation":"1982-04-07",
        "date_derniere_declaration":null,
        "date_publication_creation":"1982-04-19",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"CLT/DX HF81 CIBISTES LIBRES TARNAIS DX HAUTE FREQUENCE 81",
        "titre_court":null,
        "objet":"O",
        "objet_social1":"000000",
        "objet_social2":"000000",
        "l1_adresse_import":"8 RUE DU 19 MARS 1962",
        "l2_adresse_import":"A",
        "l3_adresse_import":"A",
        "adresse_siege":null,
        "adresse_numero_voie":null,
        "adresse_repetition":null,
        "adresse_type_voie":null,
        "adresse_libelle_voie":null,
        "adresse_distribution":null,
        "adresse_code_insee":"81105",
        "adresse_code_postal":"81300",
        "adresse_libelle_commune":"GRAULHET",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":null,
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":null,
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":null,
        "adresse_gestion_acheminement":null,
        "adresse_gestion_pays":null,
        "dirigeant_civilite":"PM",
        "telephone":null,
        "site_web":"www",
        "email":null,
        "autorisation_publication_web":null,
        "observation":"obs",
        "position_activite":"A",
        "derniere_maj":"0001-01-01  01:50:39",
        "created_at":"2022-05-03T02:08:45.000Z",
        "updated_at":"2022-05-03T02:08:45.000Z"
      },
      {
        "id":67438536,
        "is_waldec":"false",
        "id_association":"711S0711001726",
        "id_ex_association":"0711001726",
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"711S",
        "date_creation":"0001-01-01",
        "date_derniere_declaration":null,
        "date_publication_creation":"0001-01-01",
        "date_declaration_dissolution":null,
        "nature":"A",
        "groupement":"S",
        "titre":"ASSOCIATION POUR LE DEVELOPEMENT ET L'ANIMATION CLTURELS ET ARTISTIQUES EN MILIEU RURAL (ADACAR)",
        "titre_court":null,
        "objet":"AIDER AU DEVELOPPEMENT DES LOISIRS DE L'ANIMATION DE L'ACTION CULTURELLE ET ARTISTIQUE EN MILIEU RURAL",
        "objet_social1":"000000",
        "objet_social2":"000000",
        "l1_adresse_import":"MAISON DES ARTS ET LOISIRS",
        "l2_adresse_import":null,
        "l3_adresse_import":null,
        "adresse_siege":null,
        "adresse_numero_voie":null,
        "adresse_repetition":null,
        "adresse_type_voie":null,
        "adresse_libelle_voie":null,
        "adresse_distribution":null,
        "adresse_code_insee":"71153",
        "adresse_code_postal":"71200",
        "adresse_libelle_commune":"LE-CREUSOT",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":null,
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":null,
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":null,
        "adresse_gestion_acheminement":null,
        "adresse_gestion_pays":null,
        "dirigeant_civilite":"PM",
        "telephone":null,
        "site_web":null,
        "email":null,
        "autorisation_publication_web":null,
        "observation":"Reprise  =\u003e  date ag=0000-00-00",
        "position_activite":"D",
        "derniere_maj":"2008-11-03  11:57:55",
        "created_at":"2022-05-03T02:10:08.000Z",
        "updated_at":"2022-05-03T02:10:08.000Z"
      },
      {
        "id":66688352,
        "is_waldec":"false",
        "id_association":"751P00022053",
        "id_ex_association":"00022053",
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"751P",
        "date_creation":"1950-04-24",
        "date_derniere_declaration":null,
        "date_publication_creation":"0001-01-01",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"COMITE DE LIAISON DES ORGANISATIONS PROFESSIONNELLES DE TRANSPORTS ET DE LA LOGISTIQUE CLTL",
        "titre_court":null,
        "objet":"assurer une liaison entre les organismes membres et le cons eil national du patronat francais",
        "objet_social1":"023000",
        "objet_social2":"000000",
        "l1_adresse_import":null,
        "l2_adresse_import":"68        RUE Cardinet",
        "l3_adresse_import":null,
        "adresse_siege":null,
        "adresse_numero_voie":null,
        "adresse_repetition":null,
        "adresse_type_voie":null,
        "adresse_libelle_voie":null,
        "adresse_distribution":null,
        "adresse_code_insee":"75117",
        "adresse_code_postal":"75017",
        "adresse_libelle_commune":"PARIS",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":null,
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":null,
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":null,
        "adresse_gestion_acheminement":null,
        "adresse_gestion_pays":null,
        "dirigeant_civilite":"PM",
        "telephone":null,
        "site_web":null,
        "email":null,
        "autorisation_publication_web":null,
        "observation":null,
        "position_activite":"A",
        "derniere_maj":"2009-05-25  05:00:00",
        "created_at":"2022-05-03T02:08:14.000Z",
        "updated_at":"2022-05-03T02:08:14.000Z"
      },
      {
        "id":65093386,
        "is_waldec":"true",
        "id_association":"W133010243",
        "id_ex_association":null,
        "siret":null,
        "numero_reconnaissance_utilite_publique":null,
        "code_gestion":"133P",
        "date_creation":"2008-10-28",
        "date_derniere_declaration":"2012-12-05",
        "date_publication_creation":"2008-11-08",
        "date_declaration_dissolution":null,
        "nature":"D",
        "groupement":"S",
        "titre":"CALME-CLT (COLLECTIF POUR UNE ALTERNATIVE AU LIBERALISME - MARSEILLE-EST - LES CAMOINS - LA TREILLE)",
        "titre_court":"CALME-CLT",
        "objet":"rassembler les citoyens qui veulent construire une alternative de gauche au libéralisme",
        "objet_social1":"002000",
        "objet_social2":"000000",
        "l1_adresse_import":null,
        "l2_adresse_import":null,
        "l3_adresse_import":null,
        "adresse_siege":null,
        "adresse_numero_voie":"59",
        "adresse_repetition":null,
        "adresse_type_voie":"RUE",
        "adresse_libelle_voie":"de la Sariette",
        "adresse_distribution":"_",
        "adresse_code_insee":"13212",
        "adresse_code_postal":"13012",
        "adresse_libelle_commune":"Marseille",
        "adresse_gestion_nom":null,
        "adresse_gestion_format_postal":null,
        "adresse_gestion_geo":null,
        "adresse_gestion_libelle_voie":"60 CHEMIN DE PLUVENCE",
        "adresse_gestion_distribution":null,
        "adresse_gestion_code_postal":"13011",
        "adresse_gestion_acheminement":"Marseille",
        "adresse_gestion_pays":"FRANCE",
        "dirigeant_civilite":"PF",
        "telephone":null,
        "site_web":null,
        "email":null,
        "autorisation_publication_web":"0",
        "observation":null,
        "position_activite":"A",
        "derniere_maj":"2013-01-11 09:51:56",
        "created_at":"2022-05-03T02:02:58.000Z",
        "updated_at":"2022-05-03T02:02:58.000Z"
      }
    ]
  }